### PR TITLE
Replace godeps with go module for dependencies management

### PR DESCRIPTION
**Pull request by dgarros**

### CODE REVIEW

**Comment by mayuresh82** [comment]
The travis build spec relies on dep , so that will need to be changed as well ( need to add the equivalent go mod command to download the deps prior to build )

**Comment by dgarros** [comment]
@mayuresh82 I've created a new container to run the test in CI using a debian based go image.
Apparently, it's not possible to run the tests with `-race` inside Alpine, it's a known limitation today.(https://github.com/golang/go/issues/14481)
Also we can't use travis directly because with `go mod`, the project needs to be outside of the go PATH. 
With this approach we have a reproducible test environment based on docker.

The production Docker image is still based on Alpine, I've just updated the Dockerfile to use the local files instead of pulling the code from Github, this way it's possible to build the docker image for any branch.

**Comment by mayuresh82** [comment]
@dgarros  I would rather hold off on this. The go mod stuff is still considered "experimental" , and i see a lot of forum posts of possible issues with docker builds etc. I think continuing the dep stuff is fine for now for alert manager.

**Comment by dgarros** [comment]
Closing since we don't want to move to go mod yet

**Pull request closed without merging**
