### PR TITLE
Fix ns1 parser

### PR DESCRIPTION
**Pull request by mayuresh82**
Fix ns1 parser

### CODE REVIEW

**Comment by cjinfantino** [comment]
Looks like some tests aren't passing?

```
The command "make test" exited with 2.

**Comment by mayuresh82** [comment]
please dont close PRs :) if something is failing, we can fix it :)

**Comment by cjinfantino** [comment]
Whoa that’s super weird. I had no intention of closing it. I must have hit close and comment instead of just comment. My bad dude.

**Comment by mayuresh82** [comment]
no worries at all i figured it was a misclick or something

**Pull request merged**
